language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  app: test-ci-app2021
  api_key: 74c80d30-dbf7-40ee-a4d8-19faf94556b1